#!/usr/bin/env node
/**
 * gen-wiki.mjs —— 构建前置：把 Qoder 生成的 Repo Wiki（.qoder/repowiki）
 * 打包成前端可用的数据文件。
 *
 * 数据来源：
 *   - .qoder/repowiki/zh/meta/repowiki-metadata.json  → wiki_catalogs 定义分类树
 *     （name + parent_id 组成层级；根节点 27 个，与 content/ 顶层目录一一对应）
 *   - .qoder/repowiki/zh/content/<分类路径>.md         → 每个叶子/分组节点对应的正文
 *
 * 输出：src/data/wiki.generated.js
 *   export const wikiTree = [ { id, title, children:[...], docId } ]   // 侧栏折叠树
 *   export const wikiDocs = { [docId]: { title, markdown } }           // 正文（原始 md 字符串，运行时渲染）
 *
 * 处理细节：
 *   - 保留 ```mermaid 代码块（前端用 mermaid.js 渲染）
 *   - 清理 <cite>...</cite> 引用块里的 file:// 链接为纯文本（本地路径线上打不开）
 *   - 密钥脱敏：正文里若混入 api_key/token 明文，替换为 ***REDACTED***
 *
 * 运行（自动挂在 build/dev 前）：node scripts/gen-wiki.mjs
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join, resolve } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const APP_DIR = resolve(__dirname, '..')                 // vue-app/summary
const REPO_ROOT = resolve(APP_DIR, '../../..')           // 仓库根
const META = join(REPO_ROOT, '.qoder/repowiki/zh/meta/repowiki-metadata.json')
const CONTENT_DIR = join(REPO_ROOT, '.qoder/repowiki/zh/content')
const OUT = join(APP_DIR, 'src/data/wiki.generated.js')

// ---- 密钥脱敏（与 gen-code-refs 保持一致的思路）----
function redactSecrets(text) {
  return text
    .replace(/((?:api[_-]?key|secret|token|password|passwd|pwd)\s*[:=]\s*['"])([^'"]{6,})(['"])/gi,
      (_, a, _v, c) => `${a}***REDACTED***${c}`)
    .replace(/(Bearer\s+)([A-Za-z0-9._\-]{12,})/g, (_, a) => `${a}***REDACTED***`)
    .replace(/\b((?:sk|personal|ghp|xox[bap])[-_][A-Za-z0-9]{12,})\b/g, '***REDACTED***')
}

// ---- 清理正文里的本地 file:// 引用 ----
// Qoder 会插入 <cite> 块与 [xxx](file://path) 链接，线上点不开，转成纯文本。
function cleanMarkdown(md) {
  let out = md
  // [label](file://xxx) -> label
  out = out.replace(/\[([^\]]+)\]\(file:\/\/[^)]*\)/g, '$1')
  return redactSecrets(out)
}

function main() {
  if (!existsSync(META)) {
    console.warn(`[gen-wiki] 找不到 metadata：${META}，跳过（wiki 数据将为空）`)
    writeFileSync(OUT, 'export const wikiTree = []\nexport const wikiDocs = {}\n')
    return
  }

  const meta = JSON.parse(readFileSync(META, 'utf8'))
  const cats = meta.wiki_catalogs || []
  const byId = new Map(cats.map(c => [c.id, c]))

  // 还原某分类节点的层级路径（["项目概述", "项目介绍"]）
  function pathOf(c) {
    const parts = [c.name]
    let p = c.parent_id
    while (p && byId.has(p)) {
      parts.push(byId.get(p).name)
      p = byId.get(p).parent_id
    }
    return parts.reverse()
  }

  const docs = {}
  let docSeq = 0

  // 为某分类读取正文。两种命中方式：
  //   1. 叶子文档：       content/<路径>.md
  //   2. 分组概览页：     content/<路径>/<同名>.md（分组节点自己的介绍页）
  function loadDoc(parts, title) {
    const leaf = join(CONTENT_DIR, ...parts) + '.md'
    const overview = join(CONTENT_DIR, ...parts, parts[parts.length - 1] + '.md')
    const mdFile = existsSync(leaf) ? leaf : (existsSync(overview) ? overview : null)
    if (!mdFile) return null
    const raw = readFileSync(mdFile, 'utf8')
    const docId = 'd' + (docSeq++)
    docs[docId] = { title, markdown: cleanMarkdown(raw) }
    return docId
  }

  // 组装树：先建节点，再按 parent 挂接
  const nodeById = new Map()
  for (const c of cats) {
    const parts = pathOf(c)
    nodeById.set(c.id, {
      id: c.id,
      title: c.name,
      docId: loadDoc(parts, c.name),
      children: [],
    })
  }

  const roots = []
  for (const c of cats) {
    const node = nodeById.get(c.id)
    if (c.parent_id && nodeById.has(c.parent_id)) {
      nodeById.get(c.parent_id).children.push(node)
    } else {
      roots.push(node)
    }
  }

  // 保持 metadata 里的原始顺序（cats 数组顺序即导出顺序，近似 Qoder 侧栏）
  // 根节点按它们在 cats 中首次出现的顺序排列
  const rootOrder = new Map()
  cats.forEach((c, i) => {
    if (!(c.parent_id && nodeById.has(c.parent_id))) rootOrder.set(c.id, i)
  })
  roots.sort((a, b) => (rootOrder.get(a.id) ?? 0) - (rootOrder.get(b.id) ?? 0))

  const banner = `// AUTO-GENERATED by scripts/gen-wiki.mjs —— 请勿手改。源：.qoder/repowiki\n`
  const body =
    banner +
    `export const wikiTree = ${JSON.stringify(roots)}\n` +
    `export const wikiDocs = ${JSON.stringify(docs)}\n`
  writeFileSync(OUT, body)

  const kb = (Buffer.byteLength(body) / 1024).toFixed(0)
  console.log(`[gen-wiki] 分类节点 ${cats.length}，正文 ${docSeq} 篇 → ${OUT}（${kb} KB）`)
}

main()
